import UIKit

struct StringConstants {
    static let kLblTtMmYy: String = "tt/mm/yy"
    static let kLblPersonality: String = "Personality"
    static let k: String = ""
    static let kLblEditPhoto: String = "Edit Photo"
    static let kLblLastName2: String = "Last name"
    static let kLblYourEmail: String = "Your Email"
    static let kLblNext: String = "Next"
    static let kMsgResearchProduc: String = "Research Product for UI8"
    static let kLblIndonesian: String = "Indonesian"
    static let kMsgDonTHaveAnA: String = "Don’t have an account?"
    static let kLblEnglish: String = "English"
    static let kLblAdalahalcana: String = "AdalahAlcana|"
    static let kLblAdalah: String = "Adalah"
    static let kLblIndonesian2: String = "Indonesian|"
    static let kLblDateOfBirth: String = "Date of birth"
    static let kLblFirstName: String = "First Name"
    static let kMsgAlreadyHaveAn: String = "Already have an account?"
    static let kLblCountry: String = "Country"
    static let kMsgLoremIpsumDol2: String =
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla fermentum netus amet risus commodo amet vulputate tellus. Et quis ornare sed diam in. Id nibh mattis quis fermentum non malesuada. Vel ullamcorper lacus, mollis pellentesque egestas aliquet aliquam. Risus lorem velit, nunc id ornare diam. Odio diam egestas vulputate tristique mi aliquam eget. Feugiat mi sed semper faucibus tellus aliquam nulla ullamcorper arcu. Est in risus pulvinar arcu pretium dui eget pretium. Nunc, sed scelerisque id varius.\nVulputate vel aliquam suscipit vitae, nullam pretium. Ut sed elementum eget id pellentesque. Odio placerat faucibus purus rhoncus, pharetra commodo. Augue a duis vitae tempor lobortis. Aliquam nunc amet fermentum, aliquet elementum ac neque, convallis. Fames nulla ornare diam odio enim. Enim, pellentesque "
    static let kLblFirstName2: String = "First name"
    static let kLblToday: String = "Today"
    static let kLbl28May2002: String = "28 May 2002|"
    static let kMsgWhenCommunity: String = "When community comes unity"
    static let kLblLogOut: String = "Log Out"
    static let kLblSetting: String = "Setting"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kMsgYourSettingsS: String = "Your settings so that we are comfortable"
    static let kMsgThisIsYourCo: String = "this is your community, help them to grow more"
    static let kLblSignUp: String = "Sign Up"
    static let kMsgLoremIpsumDol: String =
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    static let kLblChangeSave: String = "Change save"
    static let kMsgForgotPassword: String = "Forgot Password?"
    static let kMsgWelcomeToOur: String = "Welcome to our community"
    static let kLblHobby: String = "Hobby"
    static let kLblUsername: String = "UserName"
    static let kMsgCreateActionP: String = "Create Action Plan"
    static let kLblAttachments: String = "Attachments"
    static let kLblTaskTodo: String = "Task todo"
    static let kLblSave: String = "Save"
    static let kMsgCreateActionM: String = "Create Action Mobile"
    static let kLbl02April2021: String = "02 April 2021"
    static let kMsgHelpingOthers: String = "Helping others means helping yourself. "
    static let kMsgMakeYourJobE: String = "Make your job easier with our reminders"
    static let kMsgIfYouAreAlwa: String =
        "If you are always helping others you are helping yourself too"
    static let kLblDate: String = "Date"
    static let kLblEmail: String = "Email"
    static let kLblFourta: String = "Fourta|"
    static let kLblStart: String = "Start"
    static let kLblLastName: String = "Last Name"
    static let kMsgJoined6Month: String = "Joined 6 Month Ago"
    static let kLblMaximum10Mb: String = "maximum 10 mb"
    static let kLblWorkTodayS2: String = "Work Today's"
    static let kLblLogin: String = "Login"
    static let kLblSleep: String = "Sleep|"
    static let kLblAlcanasatre: String = "Alcanasatre"
    static let kLblEMail2: String = "E-mail"
    static let kHttpFail: String = "HTTP request failed"
    static let kLblForgotPassword: String = "Forgot Password"
    static let kMsgOurCommunityI3: String =
        "Our community is always there 24 hours if you need it, don't hesitate to join"
    static let kMsgOurCommunityI2: String =
        "Our community is your community too so let's strengthen our community together"
    static let kLblPassword: String = "Password"
    static let kLblSettings: String = "Settings"
    static let kMsgOurCommunityI: String =
        "our community is ready to help you to join our best platform"
    static let kLblSignup2: String = "SignUp"
    static let kLblWorkTodayS: String = "Work Today’s"
    static let kLblLanguage: String = "Language"
    static let kLblGetInThrough: String = "Get in through"
    static let kInvalidUrl: String = "Invalid URL"
    static let kMsgMakeAWishLis: String = "Make a wish list"
    static let kMsgTermsAndCondi: String = "Terms and Conditions"
}
